services:
  postgres:
    image: postgres:latest
    hostname: postgres
    networks:
      - pub-net
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  backend:
    build: .
    networks:
      - pub-net
    depends_on:
      - postgres

networks:
  pub-net:
    external: true